# Generated by Django 5.0.1 on 2024-02-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commet',
            new_name='Comment',
        ),
    ]
