# Generated by Django 5.0.1 on 2024-02-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_commet_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_mail',
            new_name='user_email',
        ),
    ]
